### ISSUE TITLE
npm postinstall script

### ISSUE THREAD

**Issue by feimosi** [bpmn-io/bpmn.io#14]
Hi, you could simplify the setup process by adding a new entry inside the `scripts` property in the `package.json`. In my projects we're using:
```js
"scripts": {
    "postinstall": "bower install -F"
    // ...
}
```
Then only `npm install` would be enough. It's just an enhancement tip.

**Comment by nikku** [comment]
Good suggestion! Closed via b92a1123da579a7379ea5479c7bb89cac64b3ee3
