### ISSUE TITLE
add properties panel release blog post

### ISSUE THREAD

**Issue by pedesen** [bpmn-io/bpmn.io#17]
for v0.5.0

**Comment by meyerdan** [comment]
Some ideas for the highlights:

- New tabbed layout allows users to find properties faster
- Add support for Camunda Job Prioritity
- Add support for Camunda Job Retry time Cycle
- Add support for Camunda camunda:initiator
- Numerous bug fixes

Under the hood:
cleaned up styles / css / less

Probably missing some things
