### ISSUE TITLE
The content of element 'bpmn2:dataInputAssociation' is not complete. ...

### ISSUE THREAD

**Issue by voogieJames** [bpmn-io/bpmn.io#36]
Hello, 
Faced with this error while editing the diagram. 
Say, you have a 'CallActivity' and a connection to either 'DataObjectReference' or 'DataStoreReference'.  If you change the CallActivity type of the same object to any other one (Task, UserTask etc ...) and try to save it on the backend, you will get the following error: 

 The content of element 'bpmn2:dataInputAssociation' is not complete. One of '{"http://www.omg.org/spec/BPMN/20100524/MODEL":documentation, "http://www.omg.org/spec/BPMN/20100524/MODEL":extensionElements, "http://www.omg.org/spec/BPMN/20100524/MODEL":sourceRef, "http://www.omg.org/spec/BPMN/20100524/MODEL":targetRef}' is expected

But if you manually remove connection with DataObject... it works just fine.

**Comment by nikku** [comment]
Please reproduce this error against [demo.bpmn.io](https://demo.bpmn.io) and report your results. Thanks!

**Comment by voogieJames** [comment]
Hi @nikku, the issue appears to happen on the server side while saving diagram and thus sending it to the backend, where exception is thrown while parsing the XML.

**Comment by nikku** [comment]
So not an issue with our library then?

**Comment by voogieJames** [comment]
Well, I'm not sure, because maybe the XML is not saved according to the specs.

**Comment by voogieJames** [comment]
This is the exception from Camunda XMLSchemaValidator while parsing the XML generated by bpmn.io:

"Caused by: org.xml.sax.SAXException: Error: URI=null Line=33: cvc-complex-type.2.4.b: The content of element 'bpmn2:dataInputAssociation' is not complete. One of '{"http://www.omg.org/spec/BPMN/20100524/MODEL":documentation, "http://www.omg.org/spec/BPMN/20100524/MODEL":extensionElements, "http://www.omg.org/spec/BPMN/20100524/MODEL":sourceRef, "http://www.omg.org/spec/BPMN/20100524/MODEL":targetRef}' is expected."

**Comment by nikku** [comment]
> Please reproduce this error against demo.bpmn.io and report your results. Thanks!

Please provide us with concrete steps to reproduce this issue against [demo.bpmn.io](https://demo.bpmn.io) if there is anything we should act on.

* Start with an initially valid diagram
* Open in the demo
* Perform actions
* Export the diagram
* Verify whether or not the diagram is broken or not

Thanks!
