### ISSUE TITLE
Feature request: swap elements

### ISSUE THREAD

**Issue by nevries** [bpmn-io/bpmn.io#43]
I'd love a feature that makes it possible to swap two selected elements with automatic sequence/message-flow adjusting. The attached image should make it clear.
![how swapping elements would be cool](https://user-images.githubusercontent.com/31620219/41721741-0765447e-7567-11e8-9f05-1dd54a8a1f52.png)

**Comment by nikku** [comment]
Sounds like a good idea, filed in the wrong repository. Do you mind migrating this issue to [bpmn-js](https://github.com/bpmn-io/bpmn-js) or the [Camunda Modeler](https://github.com/camunda/camunda-modeler) (depending on where you'd love to see this feature).
