### ISSUE TITLE
Document Promise support

### ISSUE THREAD

**Issue by oguzeroglu** [bpmn-io/bpmn.io#71]
We should document about Promise support in bpmn-js APIs here: https://bpmn.io/l/moving-to-promises.html

---

Child of https://github.com/bpmn-io/bpmn-js/issues/812

**Comment by nikku** [comment]
Similar to https://github.com/bpmn-io/dmn-js-examples/tree/master/dmn-compatibility we are going to document callback to promise transition and link on the bpmn.io site: `https://bpmn.io/l/moving-to-promises.html`.

**Comment by nikku** [comment]
Should be a separate repository in the bpmn.io org.

**Comment by philippfromme** [comment]
What's an appropriate name for the repo? `bpmn-io-moving-to-promises`?

**Comment by nikku** [comment]
`bpmn-js-callbacks-to-promises` ?

**Comment by philippfromme** [comment]
`bpmn-js-promise-to-call-back`? Just kidding, sounds good.

**Comment by nikku** [comment]
Documented here: https://github.com/bpmn-io/bpmn-js-callbacks-to-promises
