### ISSUE TITLE
Update contributors

### ISSUE THREAD

**Issue by nikku** [bpmn-io/bpmn.io#77]
__What should we do?__

Update the project contributors on [bpmn.io](https://bpmn.io/about/).

Add Alexis + Max (if you are fine with it), make Oguz a past contributor.

__Why should we do it?__

Reflect current project team.

**Comment by utkarsh4321** [comment]
Hii @nikku can i work on this

**Comment by nikku** [comment]
No need to do that, thanks!

We'll pick that issue internally.
