### ISSUE TITLE
Use  different ports for the connect servers

### ISSUE THREAD

**Issue by zeropaper** [bpmn-io/bpmn.io#8]
In order to ease the development of the different sub-projects/dependencies, we could use different ports as follow:
- bpmn.io on port 9000 (and livereload on 9001)
- diagram-js on port 9010 (and livereload on 9011)
- bpmn-js on port 9020 (and livereload on 9021)
- moddle on port 9030 (and livereload on 9031)
- moddle-xml on port 9030 (and livereload on 9031)

This would require some modifications in the grunt files as well as livereload snippets embedded in the pages.

**Comment by JonasGroeger** [comment]
moddle on port 9030 (and livereload on 9031)
moddle-xml on port ~~9030~~ 9040 (and livereload on ~~9031~~ 9041)

**Comment by nikku** [comment]
This is kind of outdated. We have no live-reload required examples but instead rely on test cases that get a unique port assigned automatically via karma.
